name: Build EXE with PyInstaller

on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole cli.py
        shell: cmd

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: built-exe
          path: dist/cli.exe
          
  download:
    needs: build
    runs-on: ubuntu-latest  # Can be any OS since it's just downloading

    steps:
      - name: Download Built EXE
        uses: actions/download-artifact@v4
        with:
          name: built-exe
          path: downloaded-exe

      - name: List Downloaded Files
        run: ls -R downloaded-exe
